package rules.Validation.ABContactValidationRules_dir.DefaultValidationRules_dir

@gw.rules.RuleName("Require Past DOB")
internal class RequirePastDOB {
  static function doCondition(aBContact : entity.ABContact) : boolean {
    
/*start00rule*/
return (aBContact typeis ABPerson) and (aBContact.DateOfBirth) != null
/*end00rule*/

  }

  static function doAction(aBContact : entity.ABContact, actions : gw.rules.Action) {

/*start00rule*/
// Require that the DateOfBirth, if specified, is in the past.

if (gw.api.util.DateUtil.compareIgnoreTime(
    (aBContact as ABPerson).DateOfBirth,
    gw.api.util.DateUtil.currentDate() ) > 0)
  aBContact.reject( "loadsave", "Date of Birth must be in the past", null, null )
/*end00rule*/

  }
}
